video/mhl: sii8240: Don't use switch condition for boolean case
GCC 5 warns about switch condition being used against a boolean case:

  kernel/samsung/exynos5410/drivers/media/video/mhl/sii8240.c: In function
  'tmds_control':
  kernel/samsung/exynos5410/drivers/media/video/mhl/sii8240.c:356:10: error:
  switch condition has boolean value [-Werror=switch-bool]
    switch (tmds_on) {
            ^

Standard if condition should have been sufficient since all we are comparing
is against either true or false, with default case doesn't even make any sense.

Signed-off-by: Albert I <kras@raphielgang.org>